# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chuankou.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(775, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sendbutton = QtWidgets.QPushButton(self.centralwidget)
        self.sendbutton.setGeometry(QtCore.QRect(115, 266, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.sendbutton.setFont(font)
        self.sendbutton.setObjectName("sendbutton")
        self.sendcom = QtWidgets.QComboBox(self.centralwidget)
        self.sendcom.setGeometry(QtCore.QRect(100, 60, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.sendcom.setFont(font)
        self.sendcom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sendcom.setObjectName("sendcom")
        self.sendcom.addItem("")
        self.sendcom.setItemText(0, "")
        self.sendbot = QtWidgets.QComboBox(self.centralwidget)
        self.sendbot.setGeometry(QtCore.QRect(100, 160, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.sendbot.setFont(font)
        self.sendbot.setObjectName("sendbot")
        self.sendbot.addItem("")
        self.sendbot.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.recvddata = QtWidgets.QTextEdit(self.centralwidget)
        self.recvddata.setGeometry(QtCore.QRect(240, 20, 371, 281))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.recvddata.setFont(font)
        self.recvddata.setObjectName("recvddata")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 310, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.inputdata = QtWidgets.QTextEdit(self.centralwidget)
        self.inputdata.setGeometry(QtCore.QRect(260, 360, 321, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.inputdata.setFont(font)
        self.inputdata.setObjectName("inputdata")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(500, 470, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.senddata = QtWidgets.QPushButton(self.centralwidget)
        self.senddata.setGeometry(QtCore.QRect(120, 380, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.senddata.setFont(font)
        self.senddata.setObjectName("senddata")
        self.checknline = QtWidgets.QCheckBox(self.centralwidget)
        self.checknline.setGeometry(QtCore.QRect(210, 460, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checknline.setFont(font)
        self.checknline.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checknline.setObjectName("checknline")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 775, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.sendbutton.clicked.connect(MainWindow.open_com)
        self.sendcom.activated['QString'].connect(MainWindow.port_changed)
        self.sendbot.activated['QString'].connect(MainWindow.baud_changed)
        self.senddata.clicked.connect(MainWindow.senddatatocom)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sendbutton.setStatusTip(_translate("MainWindow", "点击连接"))
        self.sendbutton.setText(_translate("MainWindow", "连接"))
        self.sendbot.setItemText(0, _translate("MainWindow", "9600"))
        self.sendbot.setItemText(1, _translate("MainWindow", "115200"))
        self.label.setText(_translate("MainWindow", "串口"))
        self.label_2.setText(_translate("MainWindow", "波特率"))
        self.label_3.setText(_translate("MainWindow", "接收显示"))
        self.label_4.setText(_translate("MainWindow", "发送数据"))
        self.senddata.setText(_translate("MainWindow", "发送"))
        self.checknline.setText(_translate("MainWindow", "发送新行"))
